// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6xf3UW2mun4T2GqwqV-aNi1FiDeZhx48',
    appId: '1:418206404354:android:86cd0102978bb07816fc1b',
    messagingSenderId: '418206404354',
    projectId: 'jarental-8c681',
    storageBucket: 'jarental-8c681.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz9vhUD90cxEReDQ7unRhbBwD86-wL4ww',
    appId: '1:418206404354:web:047f3d5e094d523116fc1b',
    messagingSenderId: '418206404354',
    projectId: 'jarental-8c681',
    authDomain: 'jarental-8c681.firebaseapp.com',
    storageBucket: 'jarental-8c681.appspot.com',
    measurementId: 'G-KG4TWGRJW0',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSco6jy0eTEiDT9pahIPNahB5o76yGFZ0',
    appId: '1:418206404354:ios:b26647ed60681a8616fc1b',
    messagingSenderId: '418206404354',
    projectId: 'jarental-8c681',
    storageBucket: 'jarental-8c681.appspot.com',
    iosBundleId: 'com.jarental.jarentalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSco6jy0eTEiDT9pahIPNahB5o76yGFZ0',
    appId: '1:418206404354:ios:b26647ed60681a8616fc1b',
    messagingSenderId: '418206404354',
    projectId: 'jarental-8c681',
    storageBucket: 'jarental-8c681.appspot.com',
    iosBundleId: 'com.jarental.jarentalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz9vhUD90cxEReDQ7unRhbBwD86-wL4ww',
    appId: '1:418206404354:web:d4f95aa97dae78a416fc1b',
    messagingSenderId: '418206404354',
    projectId: 'jarental-8c681',
    authDomain: 'jarental-8c681.firebaseapp.com',
    storageBucket: 'jarental-8c681.appspot.com',
    measurementId: 'G-DPJ98D9MT8',
  );

}
