 final Map<String, List<String>> carData = {
    "Toyota": [
      "Toyota Camry",
      "Toyota Avalon",
      "Toyota Corolla",
      "Toyota Yaris",
      "Toyota RAV4",
      "Toyota Highlander",
      "Toyota 4Runner",
      "Toyota Land Cruiser",
      "Toyota Venza",
      "Toyota C-HR",
      "Toyota Sequoia",
      "Toyota Tacoma",
      "Toyota Tundra",
      "Toyota Prius",
      "Toyota Corolla Hatchback",
      "Toyota Yaris Hatchback",
      "Toyota Prius Prime",
      "Toyota RAV4 Hybrid",
      "Toyota RAV4 Prime",
      "Toyota Camry Hybrid",
      "Toyota Highlander Hybrid",
      "Toyota Sienna",
      "Toyota GR86",
      "Toyota Supra",
      "Toyota bZ4X"
    ],
    "Honda": [
      "Honda Accord",
      "Honda Civic",
      "Honda Fit",
      "Honda Insight",
      "Honda Clarity",
      "Honda HR-V",
      "Honda CR-V",
      "Honda Passport",
      "Honda Pilot",
      "Honda Odyssey",
      "Honda Ridgeline",
      "Honda Civic Type R",
      "Honda NSX",
      "Honda Element"
    ],
    "Ford": [
      "Ford F-150",
      "Ford F-250",
      "Ford F-350",
      "Ford Ranger",
      "Ford Maverick",
      "Ford Escape",
      "Ford Edge",
      "Ford Explorer",
      "Ford Expedition",
      "Ford Bronco",
      "Ford Bronco Sport",
      "Ford Mustang",
      "Ford Mustang Mach-E",
      "Ford Fiesta",
      "Ford Focus",
      "Ford Fusion",
      "Ford Transit Connect",
      "Ford Transit",
      "Ford Transit Custom"
    ],
    "Chevrolet": [
      "Chevrolet Silverado 1500",
      "Chevrolet Silverado 2500HD",
      "Chevrolet Silverado 3500HD",
      "Chevrolet Colorado",
      "Chevrolet Canyon",
      "Chevrolet Equinox",
      "Chevrolet Traverse",
      "Chevrolet Tahoe",
      "Chevrolet Suburban",
      "Chevrolet Blazer",
      "Chevrolet Trailblazer",
      "Chevrolet Camaro",
      "Chevrolet Corvette",
      "Chevrolet Malibu",
      "Chevrolet Spark",
      "Chevrolet Sonic",
      "Chevrolet Bolt EV",
      "Chevrolet Bolt EUV",
      "Chevrolet Express",
      "Chevrolet City Express"
    ],
    "Nissan": [
      "Nissan Altima",
      "Nissan Sentra",
      "Nissan Maxima",
      "Nissan Versa",
      "Nissan 370Z",
      "Nissan GT-R",
      "Nissan Leaf",
      "Nissan Kicks",
      "Nissan Juke",
      "Nissan Rogue",
      "Nissan Murano",
      "Nissan Pathfinder",
      "Nissan Armada",
      "Nissan Frontier",
      "Nissan Titan",
      "Nissan Titan XD",
      "Nissan NV Cargo",
      "Nissan NV Passenger",
      "Nissan NV200"
    ],
    "BMW": [
      "BMW 1 Series",
      "BMW 2 Series",
      "BMW 3 Series",
      "BMW 4 Series",
      "BMW 5 Series",
      "BMW 6 Series",
      "BMW 7 Series",
      "BMW 8 Series",
      "BMW X1",
      "BMW X2",
      "BMW X3",
      "BMW X4",
      "BMW X5",
      "BMW X6",
      "BMW X7",
      "BMW Z4",
      "BMW i3",
      "BMW i4",
      "BMW iX",
      "BMW M2",
      "BMW M3",
      "BMW M4",
      "BMW M5",
      "BMW M8"
    ],
    "Mercedes-Benz": [
      "Mercedes-Benz A-Class",
      "Mercedes-Benz B-Class",
      "Mercedes-Benz C-Class",
      "Mercedes-Benz E-Class",
      "Mercedes-Benz S-Class",
      "Mercedes-Benz CLS-Class",
      "Mercedes-Benz GLA-Class",
      "Mercedes-Benz GLB-Class",
      "Mercedes-Benz GLC-Class",
      "Mercedes-Benz GLE-Class",
      "Mercedes-Benz GLS-Class",
      "Mercedes-Benz G-Class",
      "Mercedes-Benz EQB",
      "Mercedes-Benz EQC",
      "Mercedes-Benz EQS",
      "Mercedes-Benz SL-Class",
      "Mercedes-Benz SLC-Class",
      "Mercedes-Benz AMG GT",
      "Mercedes-Benz AMG A 35",
      "Mercedes-Benz AMG C 63",
      "Mercedes-Benz AMG E 63",
      "Mercedes-Benz AMG G 63"
    ],
    "Audi": [
      "Audi A1",
      "Audi A3",
      "Audi A4",
      "Audi A5",
      "Audi A6",
      "Audi A7",
      "Audi A8",
      "Audi Q2",
      "Audi Q3",
      "Audi Q4 e-tron",
      "Audi Q5",
      "Audi Q7",
      "Audi Q8",
      "Audi TT",
      "Audi TT RS",
      "Audi R8",
      "Audi e-tron",
      "Audi e-tron GT",
      "Audi SQ5",
      "Audi S4",
      "Audi S6",
      "Audi S7",
      "Audi S8",
      "Audi RS5",
      "Audi RS7",
      "Audi RS Q8"
    ],
    "Volkswagen": [
      "Volkswagen Golf",
      "Volkswagen Golf GTI",
      "Volkswagen Golf R",
      "Volkswagen Jetta",
      "Volkswagen Passat",
      "Volkswagen Arteon",
      "Volkswagen Polo",
      "Volkswagen ID.3",
      "Volkswagen ID.4",
      "Volkswagen ID.7",
      "Volkswagen Tiguan",
      "Volkswagen Atlas",
      "Volkswagen Atlas Cross Sport",
      "Volkswagen Taos",
      "Volkswagen Beetle",
      "Volkswagen Atlas Tanoak",
      "Volkswagen Arteon Shooting Brake"
    ],
    "Hyundai": [
      "Hyundai Accent",
      "Hyundai Elantra",
      "Hyundai Sonata",
      "Hyundai Azera",
      "Hyundai Ioniq",
      "Hyundai Kona",
      "Hyundai Kona Electric",
      "Hyundai Tucson",
      "Hyundai Santa Fe",
      "Hyundai Santa Cruz",
      "Hyundai Palisade",
      "Hyundai Venue",
      "Hyundai Nexo",
      "Hyundai Genesis G70",
      "Hyundai Genesis G80",
      "Hyundai Genesis G90"
    ],
    "Kia": [
      "Kia Rio",
      "Kia Forte",
      "Kia K5",
      "Kia Cadenza",
      "Kia Stinger",
      "Kia Seltos",
      "Kia Sportage",
      "Kia Niro",
      "Kia Sorento",
      "Kia Telluride",
      "Kia Soul",
      "Kia EV6",
      "Kia Niro EV",
      "Kia Carnival",
      "Kia Stonic"
    ],
    "Subaru": [
      "Subaru Impreza",
      "Subaru Legacy",
      "Subaru Outback",
      "Subaru Crosstrek",
      "Subaru Forester",
      "Subaru Ascent",
      "Subaru BRZ",
      "Subaru WRX",
      "Subaru WRX STI",
      "Subaru Solterra",
      "Subaru Baja"
    ],
    "Lexus": [
      "Lexus ES",
      "Lexus GS",
      "Lexus LS",
      "Lexus IS",
      "Lexus NX",
      "Lexus RX",
      "Lexus GX",
      "Lexus LX",
      "Lexus UX",
      "Lexus LC",
      "Lexus LC Convertible",
      "Lexus RCF",
      "Lexus LFA",
      "Lexus RXh",
      "Lexus NXh",
      "Lexus UXh",
      "Lexus LS500h",
      "Lexus ES300h"
    ],
    "Mazda": [
      "Mazda2",
      "Mazda3",
      "Mazda6",
      "Mazda MX-5 Miata",
      "Mazda CX-3",
      "Mazda CX-30",
      "Mazda CX-5",
      "Mazda CX-50",
      "Mazda CX-9",
      "Mazda CX-90",
      "Mazda MX-30",
      "Mazda6 Wagon",
      "Mazda RX-7",
      "Mazda RX-8"
    ],
    "Jeep": [
      "Jeep Cherokee",
      "Jeep Grand Cherokee",
      "Jeep Grand Cherokee L",
      "Jeep Compass",
      "Jeep Renegade",
      "Jeep Wrangler",
      "Jeep Wrangler 4xe",
      "Jeep Gladiator",
      "Jeep Wagoneer",
      "Jeep Grand Wagoneer",
      "Jeep Commander"
    ],
    "Dodge": [
      "Dodge Charger",
      "Dodge Challenger",
      "Dodge Durango",
      "Dodge Journey",
      "Dodge Viper",
      "Dodge Neon",
      "Dodge Dakota",
      "Dodge Grand Caravan",
      "Dodge Ram"
    ],
    "Chrysler": [
      "Chrysler 300",
      "Chrysler Pacifica",
      "Chrysler Voyager",
      "Chrysler Aspen",
      "Chrysler Sebring",
      "Chrysler PT Cruiser",
      "Chrysler 200",
      "Chrysler Crossfire"
    ],
    "Cadillac": [
      "Cadillac CT4",
      "Cadillac CT5",
      "Cadillac CT6",
      "Cadillac XTS",
      "Cadillac ATS",
      "Cadillac CTS",
      "Cadillac Escalade",
      "Cadillac XT4",
      "Cadillac XT5",
      "Cadillac XT6",
      "Cadillac LYRIQ",
      "Cadillac Eldorado",
      "Cadillac SRX"
    ],
    "Tesla": [
      "Tesla Model S",
      "Tesla Model 3",
      "Tesla Model X",
      "Tesla Model Y",
      "Tesla Cybertruck",
      "Tesla Roadster",
      "Tesla Semi"
    ],
    "Volvo": [
      "Volvo S60",
      "Volvo S90",
      "Volvo V60",
      "Volvo V90",
      "Volvo XC40",
      "Volvo XC60",
      "Volvo XC90",
      "Volvo EX30",
      "Volvo EX90",
      "Volvo C40 Recharge",
      "Volvo XC100 Recharge"
    ],
    "Land Rover": [
      "Land Rover Defender",
      "Land Rover Discovery",
      "Land Rover Discovery Sport",
      "Land Rover Range Rover",
      "Land Rover Range Rover Sport",
      "Land Rover Range Rover Velar",
      "Land Rover Range Rover Evoque",
      "Land Rover Freelander",
      "Land Rover LR4",
      "Land Rover LR2"
    ],
    "Jaguar": [
      "Jaguar XE",
      "Jaguar XF",
      "Jaguar XJ",
      "Jaguar E-Pace",
      "Jaguar F-Pace",
      "Jaguar I-Pace",
      "Jaguar F-Type",
      "Jaguar X-Type",
      "Jaguar XK"
    ],
    "Porsche": [
      "Porsche 718 Cayman",
      "Porsche 718 Boxster",
      "Porsche 911 Carrera",
      "Porsche 911 Turbo",
      "Porsche 911 GT3",
      "Porsche Panamera",
      "Porsche Taycan",
      "Porsche Macan",
      "Porsche Cayenne",
      "Porsche Cayenne Coupe",
      "Porsche 918 Spyder",
      "Porsche 944",
      "Porsche 928"
    ],
    "Acura": [
      "Acura ILX",
      "Acura TLX",
      "Acura RLX",
      "Acura MDX",
      "Acura RDX",
      "Acura ZDX",
      "Acura NSX",
      "Acura CL",
      "Acura TSX"
    ],
    "Infiniti": [
      "Infiniti Q50",
      "Infiniti Q60",
      "Infiniti Q70",
      "Infiniti QX50",
      "Infiniti QX55",
      "Infiniti QX60",
      "Infiniti QX80",
      "Infiniti FX",
      "Infiniti EX",
      "Infiniti JX35"
    ],
    "Mitsubishi": [
      "Mitsubishi Mirage",
      "Mitsubishi Mirage G4",
      "Mitsubishi Lancer",
      "Mitsubishi Galant",
      "Mitsubishi Outlander",
      "Mitsubishi Outlander Sport",
      "Mitsubishi Eclipse Cross",
      "Mitsubishi Pajero",
      "Mitsubishi Montero",
      "Mitsubishi L200"
    ],
    "Peugeot": [
      "Peugeot 208",
      "Peugeot 2008",
      "Peugeot 308",
      "Peugeot 3008",
      "Peugeot 5008",
      "Peugeot 508",
      "Peugeot 508 SW",
      "Peugeot Partner",
      "Peugeot Rifter",
      "Peugeot Expert",
      "Peugeot Boxer",
      "Peugeot 3008 Hybrid",
      "Peugeot 508 Plug-in Hybrid"
    ],
    "Renault": [
      "Renault Clio",
      "Renault Captur",
      "Renault Megane",
      "Renault Kadjar",
      "Renault Koleos",
      "Renault Talisman",
      "Renault Twingo",
      "Renault Zoe",
      "Renault Arkana",
      "Renault Master",
      "Renault Trafic",
      "Renault Kangoo",
      "Renault Scenic",
      "Renault Espace"
    ],
    "Fiat": [
      "Fiat 500",
      "Fiat 500X",
      "Fiat 500L",
      "Fiat Panda",
      "Fiat Tipo",
      "Fiat 124 Spider",
      "Fiat 500e",
      "Fiat Doblo",
      "Fiat Fiorino",
      "Fiat Ducato",
      "Fiat Panda Cross",
      "Fiat Linea",
      "Fiat Multipla"
    ],
    "Alfa Romeo": [
      "Alfa Romeo Giulia",
      "Alfa Romeo Stelvio",
      "Alfa Romeo Giulietta",
      "Alfa Romeo 4C",
      "Alfa Romeo 8C Competizione",
      "Alfa Romeo GTV",
      "Alfa Romeo Alfetta"
    ],
  };
 